version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI
      - PORT
      - CLIENT_URL
      - FRONTEND_REDIRECT_URL
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - JWT_SECRET
      - CLOUDINARY_CLOUD_NAME
      - CLOUDINARY_API_KEY
      - CLOUDINARY_API_SECRET